name: Deploy to ACI

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Login to Azure using the Azure CLI Action
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 2: Deploy to Azure Container Instances using Azure CLI
      - name: 'Deploy to Azure Container Instances'
        run: |
          az container create \
            --resource-group myResourceGroup \
            --name mycontainerinstance \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/app:latest \
            --dns-name-label myappdeployment \
            --ports 80 \
            --cpu 1 \
            --memory 1.5 \
            --location eastus