name: Deploy Next.js and FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --confirm

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Deploy FastAPI
        run: |
          # Commands to deploy FastAPI on your chosen platform, e.g., Railway CLI
          railway up  # Adjust as per your platform’s deployment command