name: Deploy to ACI

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Login to ACR
      - name: Login to ACR
        run: |
          az acr login --name mycontainerregistrygng5300a

      # Step 4: Build and push the Docker image
      - name: Deploy container to ACI
        run: |
          az container create \
            --resource-group MyResourceGroup \
            --name nextjsfastapi \
            --image mycontainerregistrygng5300a.azurecr.io/app:lateset \
            --cpu 1 \
            --memory 1.5 \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
            --dns-name-label <dns-label> \
            --ports 80
